1sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.4.7'
before_script:
  - npm prune
script:
  - npm run test:coverage
after_success:
  - npm run report:coverage
  - npm run semantic:release
